apiVersion: v1
kind: Service
metadata:
  name: ws-exposer
spec:
  selector:
    app: ws-servers
  ports:
    - name: port-3000
      protocol: 'TCP'
      port: 3000
      targetPort: 3000  
    - name: port-5000
      protocol: 'TCP'
      port: 5000
      targetPort: 5000  
  type: LoadBalancer    